import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import Breadcrumbs from '../components/Breadcrumbs/Breadcrumbs'

export default function Collection() {
    return (
        <MainLayout>
            <Head>
                <title>Homebody Collection Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <Breadcrumbs />
            </div>
        </MainLayout>
    )
}