import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import Breadcrumbs from '../components/Breadcrumbs/Breadcrumbs'
import Banner1 from '../components/Banner/Banner1/Banner1'
import Collectiongrid from '../components/Collections/Collectiongrid/Collectiongrid'

export default function Collection() {
    return (
        <MainLayout>
            <Head>
                <title>Homebody Collection Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Banner1 bannerbg={'https://www.accraecommerce.com/htmlemailimages/decorbg.png'} bannerTitle={'Home decor'}/>
            <div className="container">
                <Breadcrumbs firstCrumb={'Collection'}/>
                <Collectiongrid />
            </div>
        </MainLayout>
    )
}