import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import Breadcrumbs from '../components/Breadcrumbs/Breadcrumbs'
import ProductMain1 from '../components/ProductMain/ProductMain1/ProductMain1'

export default function Product() {
    return (
        <MainLayout>
            <Head>
                <title>Homebody Product Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <Breadcrumbs />
                <ProductMain1 />
            </div>
        </MainLayout>
    )
}